### ISSUE TITLE
Missing airports from IATA

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#175]
Comparing the latest data from [IATA](https://www.iata.org/en/publications/directories/code-search/) with the latest data here, I find 66 missing entries. After removing all POR that are considered retired in OPTD, this comes down to 34 (this means that either a few retired POR appear on IATA website, or some codes have been reassigned and we need to fix those also).
For those 34, I will split those in 2 categories: those who appear in [OurAirports](https://davidmegginson.github.io/ourairports-data/airports.csv), and those who don't.

The first category contains 12 entries, here they are with the associated data from OurAirports:

- [x] `AZJ`: Zhenjiang^Zhenjiang Dalu Airport^small_airport^32.23649^119.718683
- [x] `CTV`: Saurimo^Catoca Airport^small_airport^-9.430985^20.311478
- [x] `EHU`: Ezhou^Ezhou Huahu Airport (under construction)^closed^30.341178^115.03926
- [x] `FZL`: Fuzuli^Fizuli Airport^small_airport^39.594578^47.196128
- [x] `GDB`: Gondia^Gondia Airport^small_airport^21.526817^80.290347
- [x] `HZU`: Chengdu^Chengdu Huaizhou Airport^medium_airport^30.677339^104.529397
- [x] `IUP`: Apui^Apuí Airport^small_airport^-7.172773^-59.8396
- [x] `JHF`: Sao Roque^São Paulo Catarina Executive Airport^medium_airport^-23.426886^-47.165658
- [x] `LMV`: Madivaru^Madivaru Airport^small_airport^5.457545^73.370261
- [x] `OYC`: CAMOPI^Camopi Airport^small_airport^3.172847^-52.336142
- [x] `TXC`: Orsha^Orsha Airport - Balbasovo Air Base^medium_airport^54.439999^30.2967
- [x] `WHB`: Eliwana^Eliwana^medium_airport^-22.428395^116.887879

And here is the second category (22 airports):

- [x] `AXO`: Pantar (Alor) [[#12402416](https://www.geonames.org/12402416/pantar-airport.html)]
- [x] `DFA`: Danfeng Shangzhen Gen. (Shangluo) [[#12402416](https://www.geonames.org/12402445) [#1796068](https://www.geonames.org/1796068)]
- [x] `DSY`: Dara Sakor Internation (Krong Khemara Phoumin) [[#12402417](https://www.geonames.org/12402417/dara-sakor-international-airport.html)]
- [x] `DZH`: Dazhou Jinya (Dazhou) [[#12402418](https://www.geonames.org/12402418/dazhou-jinya-airport.html)]
- [x] `EEA`: Reg do Planalto Serano (Correia) [[#12402419](https://www.geonames.org/12402419) [#3465409](https://www.geonames.org/3465409)]
- [x] `EES`: Berenice International (Berenice) [[#12402441](https://www.geonames.org/12402441) [#359073](https://www.geonames.org/359073)]
- [x] `GYO`: Blangkejeren (Blangkejeren) [[#12402442](https://www.geonames.org/12402442) [#1215338](https://www.geonames.org/1215338)]
- [x] `HLJ`: Beidahuang General (Zhaodong) [[#12402420](https://www.geonames.org/12402420) [#2033168](https://www.geonames.org/2033168)]
- [ ] `HSF`: Suifenhe Dongning (Suifenhe)
- [x] `IZE`: EDHF Airport (Itzehoe) [[#3208309](https://www.geonames.org/3208309) [#2895569](https://www.geonames.org/2895569)]
- [x] `JCS`: Aeroporto De Crateus (Crateus) [[#3401549](https://www.geonames.org/3401549) [#3401548](https://www.geonames.org/3401548)]
- [x] `JDE`: Jiande Qiandaohu (Jiande) [[#11493753](https://www.geonames.org/11493753)]
- [x] `JPY`: Paraty (Paraty) [[#12238281](https://www.geonames.org/12238281) [#3455036](https://www.geonames.org/3455036)]
- [x] `JSB`: Walfrido Salmito de Al (Sao Benedito) [[#12402423](https://www.geonames.org/12402423) [#3389023](https://www.geonames.org/3389023)]
- [x] `JTA`: Pedro Teixeira Castelo (Taua) [[#3402698](https://www.geonames.org/3402698) [#3386551](https://www.geonames.org/3386551)]
- [x] `JTN`: Antonio R. Nogueira Jr (Itanhaem) [[#12402440](https://www.geonames.org/12402440) [#3460791](https://www.geonames.org/3460791)]
- [x] `NVM`: Brigadeiro Eduardo Gom (Nova Mutum) [[#12402443](https://www.geonames.org/12402443) [#6317755](https://www.geonames.org/6317755)]
- [x] `RDL`: Bardawil International (New Ismailia) [[#12402444](https://www.geonames.org/12402444) [#361055](https://www.geonames.org/361055)]
- [x] `RPU`: Urucu (Coari) [[#8532021](https://www.geonames.org/8532021)]
- [x] `TBX`: Tambelan (Tambelan) [[#12402421](https://www.geonames.org/12402421) [#1625292](https://www.geonames.org/1625292)]
- [ ] `TYC`: Taiyuan Yaocheng (Taiyuan)
- [x] `UHS`: Aleksandrovsk-Sakhalin (Aleksandrovsk-Sakhalin) [[#11459287](https://www.geonames.org/11459287) [#2127282](https://www.geonames.org/2127282)]

Note that I opened [an issue](https://github.com/davidmegginson/ourairports-data/issues/3) on their repo about those.

**Comment by alexprengere** [comment]
This is almost so I will close this and open a new issue summarizing the remaining differences with IATA.
